trigger:
- main

pool:
  name: 'SelfHostedPool'  # Nome do pool onde o agente self-hosted está registrado
  demands:
    - agent.name -equals UbuntuVM  # Certifique-se de usar o nome correto do agente


variables:
  buildConfiguration: 'Release'
  vmIp: '20.206.146.25'  # Substitua pelo IP da sua VM
  vmUsername: 'mpnroot'  # Substitua pelo usuário da VM
  vmPath: '/var/www/meusite'  # Caminho na VM onde o app será colocado

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x' # Versão do .NET

- script: |
    dotnet restore
    dotnet build --configuration $(buildConfiguration)
    dotnet publish --configuration $(buildConfiguration) --output ./publish
  displayName: 'Build and Publish the App'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'DeployVM'
    sourceFolder: '$(Build.SourcesDirectory)/publish'
    targetFolder: '$(vmPath)'
    cleanTargetFolder: true

- task: SSH@0
  inputs:
    sshEndpoint: 'DeployVM'
    script: |
      sudo systemctl stop nginx
      sudo cp -r $(vmPath)/* /var/www/meusite
      sudo systemctl start nginx
  displayName: 'Deploy and Restart Nginx'

